language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0

gemfile:
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile

before_script:
  - bundle exec rake db:migrate
  - bundle exec rake app:db:test:prepare

script: bundle exec rake
